### ISSUE TITLE
manifest.xml has invalid entries

### ISSUE THREAD

**Issue by michaelchien1972** [ED6E0F17/brillo_device_raspberrypi#1]
In order to repo sync entire source code, I have to remove following entries in manifest.xml
`<project path="system/vold" name="platform/system/vold" groups="bdk" />
  <project path="libnativehelper" name="platform/libnativehelper" groups="bdk" />
  <project path="prebuilts/build-tools" name="platform/prebuilts/build-tools" groups="bdk" clone-depth="1" />
  <project path="external/lzop" name="platform/external/lzop" groups="bdk" />
  <project path="device/aaeon/upboard" name="device/aaeon/upboard" groups="upboard" />
  <project path="system/sepolicy" name="platform/system/sepolicy" groups="bdk" />
  <project path="external/lz4" name="platform/external/lz4" groups="bdk" />
  <project path="hardware/bsp/imagination" name="platform/hardware/bsp/imagination" groups="creatorci41" />
  <project path="system/tools/bpt" name="platform/system/tools/bpt" groups="bdk" />
  <project path="device/pifoundation/rpi3" name="device/pifoundation/rpi3" groups="rpi" />
  <project path="device/imagination/creatorci41" name="device/imagination/creatorci41" groups="creatorci41" />
  <project path="external/bvb" name="platform/external/bvb" groups="bdk" />
  <project path="external/libconstrainedcrypto" name="platform/external/libconstrainedcrypto" groups="bdk" />
`
Can you check if this make sense to your latest source code

Thank you

**Comment by ED6E0F17** [comment]
I don`t understand that, but almost all of those are unchanged from  "android.googlesource.com/brillo/manifest" and it needs everything except the devices.

I have never done a clean install from an empty manifest, but I will be able to test that at the weekend. I cannot see that Google have changed anything significant this week.

**Comment by ED6E0F17** [comment]
Thanks for pointing that out. Should be working now.
